# Generated by Django 4.2.15 on 2025-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcard",
            name="card_type",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")],
                default="debit",
                max_length=10,
            ),
        ),
    ]
