# Generated by Django 4.2.15 on 2025-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("nepalese_rupees", "Nepalese Rupees"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("current", "Current"),
                    ("savings", "Savings"),
                    ("fixed", "Fixed"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
