# Generated by Django 4.2.15 on 2025-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_profile_deleted_at_profile_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofkin",
            name="email_address",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                verbose_name="Email Address",
            ),
        ),
    ]
