# Generated by Django 4.2.15 on 2025-08-11 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="contentview",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_deletes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AddField(
            model_name="contentview",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Deleted"
            ),
        ),
        migrations.AlterField(
            model_name="contentview",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
                verbose_name="Content Type",
            ),
        ),
        migrations.AlterField(
            model_name="contentview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="content_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
