# Generated by Django 4.2.15 on 2025-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_bankaccount_interest_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="inactive",
                max_length=10,
                verbose_name="Account Status",
            ),
        ),
    ]
