# Generated by Django 4.2.15 on 2025-09-16 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_transaction_deleted_at_transaction_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyBalanceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Month End Balance",
                    ),
                ),
                ("month", models.DateField(db_index=True, verbose_name="Month")),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_balances",
                        to="accounts.bankaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Balance History",
                "verbose_name_plural": "Monthly Balance Histories",
                "ordering": ["-month"],
                "unique_together": {("bank_account", "month")},
            },
        ),
    ]
