# Generated by Django 4.2.15 on 2025-08-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="failed_logins",
            new_name="failed_login_attempts",
        ),
    ]
