# Generated by Django 4.2.15 on 2025-08-11 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_rename_failed_logins_user_failed_login_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_deletes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Deleted"
            ),
        ),
    ]
