# Generated by Django 4.2.15 on 2025-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_user_deleted_at_user_deleted_by_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("account_executive", "Account Executive"),
                    ("teller", "Teller"),
                    ("branch_manager", "Branch Manager"),
                    ("business_client", "Business Client"),
                ],
                default="customer",
                verbose_name="Role",
            ),
        ),
    ]
